Repository abukhadraop-or/reverifi-api, pull requests merged in 2022-02, with the labels that each got.

#18 REV-48 my profile page
  src/controllers/auth.js
  src/controllers/listing.js
  src/controllers/user.js
  src/middleware/auth.js
  src/migrations/20220127133443-modify-user-info-and-listing-tables.js
  src/migrations/20220131125749-update-user-infos-table.js
  src/migrations/20220201130109-modify-company-and-user-infos-table.js
  src/models/base-model.js
  src/models/company.js
  src/models/user-info.js
  src/routes/users.js
  src/seeders/20220123110051-add-user.js
  src/seeders/20220123110101-add-listings.js
  src/swagger.yml
Labels: Ready For Code Review, Ready For Feature Review

#17 Fix get listing endpoint
  README.md
  src/controllers/listing.js
  src/models/features.js
  src/models/listing-features.js
  src/models/listing.js
  src/routes/listings.js
  src/seeders/20220202143449-add-listing-features.js
  src/swagger.yml
Labels: Ready For Code Review, Ready For Feature Review

#16 REV-25-fetch agents and pagination and type search
  src/controllers/user.js
  src/migrations/20220125125318-add-property-type-listing-type-tables.js
  src/migrations/20220131125749-update-user-infos-table.js
  src/models/listing.js
  src/routes/users.js
  src/seeders/20220126103131-add-agent-users-and-usersInfos-and-companies.js
  src/seeders/20220126103153-add-users-roles.js
  src/seeders/20220202141618-delete-listings.js
  src/seeders/20220202141629-add-new-listings.js
  src/swagger.yml
Labels: Ready For Code Review, Ready For Feature Review

#19 Resolve the local changes on package-lock.json
  .github/workflows/cicd.yml
Labels: Passed Code Review, Ready To Merge

#20 fix update user info
  src/controllers/user.js
Labels: Passed Code Review, Ready To Merge

#22 fix pagination issue
  src/controllers/user.js
Labels: Ready For Code Review

#26 REV-111-find-an-agent-filtration-and-search-issues
  src/controllers/user.js
Labels: Ready For Code Review, Comments Addressed

#24 REV-109 search listings backend
  src/models/listing.js
  src/seeders/20220209151409-add-listing-with-roles.js
Labels: Ready For Code Review

#27 REV-112-profile-page-design-and-functionalities-issues
  src/controllers/user.js
Labels: Ready For Code Review

#29 REV-121 my listings
  .eslintrc
  src/controllers/listing.js
  src/models/base-model.js
  src/models/listing.js
  src/swagger.yml
Labels: In Code Review, Comments Addressed

#28 REV-124-agent-detailed-page-connect-to-backend
  src/controllers/listing.js
  src/controllers/user.js
  src/migrations/20220213162737-modify-user-info-about-me-field.js
  src/models/user-info.js
  src/routes/listings.js
  src/routes/users.js
  src/swagger.yml
Labels: In Code Review, Comments Addressed

#30 fix my profile bugs
  src/controllers/user.js
Labels: Ready For Code Review

#31 fixed searsh by name
  src/controllers/listing.js
  src/controllers/user.js
  src/models/listing.js
Labels: Ready For Code Review

#32 fix company email issue
  src/migrations/20220220093710-modify-company-table.js
  src/models/company.js
Labels: Passed Code Review, Ready To Merge

#33 REV-158-remove-s-from-apartments-and-add-s-to-garage-back-end
  src/migrations/20220220132623-modify-listings-table-garage-column.js
  src/models/listing.js
  src/seeders/20220123110101-add-listings.js
  src/seeders/20220202141618-delete-listings.js
  src/seeders/20220202141629-add-new-listings.js
  src/seeders/20220209151409-add-listing-with-roles.js
  src/seeders/20220220131253-modify-property-type-table-data.js
  src/swagger.yml
Labels: Passed Code Review, Ready To Merge

#34 fix property type seed
  src/seeders/20220220131253-modify-property-type-table-data.js
Labels: Passed Code Review, Ready To Merge

#35 remove comany email constaint
  src/migrations/20220221083102-modify-comany-table-email-constraint.js
Labels: Passed Code Review, Ready To Merge

#37 REV-162 update schedule
  src/controllers/listing.js
  src/migrations/20220223113121-create-schedule-table.js
  src/models/index.js
  src/models/listing.js
  src/models/schedule.js
  src/routes/index.js
  src/routes/schedule.js
  src/swagger.yml
Labels: Passed Code Review, Ready To Merge

#39 REV-164-create-listings-page-stats
  src/controllers/social-statistics.js
  src/migrations/20220226123710-create-social-statistics-and-saved-users-listings-tables.js
  src/models/index.js
  src/models/listing.js
  src/models/saved-users-listings.js
  src/models/social-statistics.js
  src/models/user.js
  src/routes/index.js
  src/routes/social-statistics.js
  src/swagger.yml
Labels: Ready For Code Review
