Repository abukhadraop-or/reverifi-api, pull requests merged in 2022-03, with the labels that each got.

#36 REV-150-agent-profile-rate-and-review
  src/controllers/review.js
  src/migrations/20220222131015-create-reviews-ratings-and-review-ratings-tables.js
  src/models/index.js
  src/models/rating-criteria.js
  src/models/review-ratings.js
  src/models/reviews.js
  src/models/user.js
  src/routes/index.js
  src/routes/rating-criteria.js
  src/routes/reviews.js
  src/seeders/20220222133140-add-user-ratings.js
  src/swagger.yml
Labels: Passed Code Review

#40 REV-153-create-listings-implement-special-tags
  src/controllers/listing.js
Labels: Passed Code Review

#41 REV-171-create-saved-listings-tab
  src/controllers/social-statistics.js
  src/models/listing-type.js
  src/models/listing.js
  src/models/property-type.js
  src/routes/social-statistics.js
  src/swagger.yml
Labels: In Code Review, Comments Addressed

#43 REV-252-search-listing-data-are-not-rendering-correctly
  src/controllers/listing.js
  src/models/listing.js
Labels: Passed Code Review, Ready To Merge

#44 add new listings seed
  src/seeders/20220307083034-add-listings-with-address.js
Labels: Ready For Code Review

#45 REV-208-rate-review-the-order-of-the-rates-selection-if-same-rates-are-selected-is-not-the-same-from-a-review-to-another-backend
  src/controllers/review.js
Labels: Ready For Code Review

#46 REV-246-edit-listing-i-am-seller-and-seller-agent-buttons-features-updates
  src/controllers/listing.js
Labels: Passed Code Review

#47 fix create listing bug
  src/controllers/listing.js
Labels: Ready For Code Review

#49 REV-285-step-01-invitation-feature
  src/controllers/auth.js
  src/controllers/user.js
  src/migrations/20220309142533-add-active-column-to-users-table.js
  src/models/user.js
  src/routes/users.js
  src/swagger.yml
Labels: In Code Review

#52 REV-319-saved-listing-the-most-recent-saved-listing-should-be-at-the-top-of-the-table
  src/controllers/social-statistics.js
Labels: Passed Code Review, Ready To Merge

#50 REV-315-dashboard-invitation-table
  src/controllers/invitation.js
  src/migrations/20220310090153-create-invitations-and-invitaion-type-tables.js
  src/models/index.js
  src/models/invitations.js
  src/models/listing.js
  src/models/user.js
  src/routes/index.js
  src/routes/invitations.js
  src/swagger.yml
Labels: In Code Review, Comments Addressed

#51 REV-314 update search price filters
  src/controllers/listing.js
  src/models/listing.js
Labels: In Code Review, Comments Addressed

#53 REV-345-create-transaction-steps-tables-backend
  src/migrations/20220313133534-create-transaction-tables.js
  src/models/index.js
  src/models/listing.js
  src/models/processes.js
  src/models/shared-columns.js
  src/models/states.js
  src/models/transaction-assignee.js
  src/models/transaction-processes.js
  src/models/transaction-workflow-steps.js
  src/models/transactions-notes.js
  src/models/transactions.js
  src/models/user.js
  src/seeders/20220313134950-add-transaction-workflows-steps-and-states-and-processes.js
Labels: In Code Review, Comments Addressed

#56 REV-300 create transactions page
  src/controllers/listing.js
  src/controllers/transaction.js
  src/models/listing.js
  src/models/transaction-assignee.js
  src/models/user.js
  src/routes/index.js
  src/routes/listings.js
  src/routes/processes.js
  src/routes/transactions.js
Labels: Ready For Code Review

#55 REV-346-connect-step-01-step-02
  src/controllers/transaction.js
  src/routes/transactions.js
Labels: Passed Code Review

#58 REV-390-uploading-assets
  .gitignore
  docker-compose.yml
  package-lock.json
  package.json
  src/config/config.js
  src/routes/index.js
  src/routes/upload.js
  src/swagger.yml
Labels: Ready For Code Review

#48 Implement points module
  src/controllers/action-types.js
  src/controllers/auth.js
  src/controllers/user-action-types.js
  src/migrations/20220308133109-create_action_types.js
  src/models/action-types.js
  src/models/user-action-types.js
  src/models/user.js
  src/routes/action-types.js
  src/routes/index.js
  src/routes/user-action-types.js
  src/seeders/20220309100144-add-action-types.js
  src/swagger.yml
Labels: Needs Rebase, In Code Review, Comments Addressed

#61 REV-418-transaction-for-the-recipient-when-the-deal-is-closed
  src/controllers/listing.js
Labels: Ready For Code Review

#59 REV-398-transaction-flow-step-3
  package-lock.json
  src/controllers/transaction.js
  src/migrations/20220319145855-create-documents-and-documents-names-tables.js
  src/models/documents-names.js
  src/models/documents.js
  src/models/index.js
  src/models/states.js
  src/models/transactions.js
  src/models/user.js
  src/routes/transactions.js
  src/routes/upload.js
  src/seeders/20220319150324-add-documents-names.js
Labels: Ready For Code Review

#57 Social login and signup
  package-lock.json
  package.json
  src/controllers/auth.js
  src/migrations/20220320091243-add_login_providers_table.js
  src/models/index.js
  src/models/login-providers.js
  src/models/user.js
  src/routes/auth.js
Labels: Ready For Code Review

#63 REV-412-transaction-the-user-should-be-able-to-go-to-the-four-transaction-flow-steps-from-my-transactions-table
  src/controllers/transaction.js
Labels: Ready For Code Review

#62 REV-167-offers-table purchase counter offer forms
  src/controllers/purchase-offer.js
  src/controllers/user.js
  src/migrations/20220317134950-create-purchase-offer.js
  src/models/index.js
  src/models/listing.js
  src/models/purchase-offer.js
  src/models/user.js
  src/routes/index.js
  src/routes/offer.js
  src/routes/users.js
Labels: Ready For Code Review

#66 REV-440-step-01-updates
  src/controllers/user.js
Labels: Unaddressed Comments

#74 REV-457-transaction-uploads-are-the-same-once-uploaded-for-all-transactions
  src/controllers/transaction.js
  src/routes/transactions.js
Labels: Passed Code Review

#75 REV-463-update-docs-title-for-nj-only
  src/seeders/20220321100059-add-new-documents-names.js
Labels: Ready For Code Review

#77 REV-444-step-02-dates-should-be-single-date
  src/migrations/20220322094410-change-tranaction-duedate-type.js
  src/models/transaction-processes.js
Labels: Passed Code Review, Ready To Merge

#76 REV-468-profile-page-profile-image-is-not-working
  src/controllers/user.js
Labels: Ready For Code Review

#79 REV-399 add final selling price
  src/controllers/transaction.js
  src/migrations/20220322115003-add-price-field-in-transactions.js
  src/models/transactions.js
Labels: Passed Code Review, Ready To Merge

#78 REV-456-create-listing-edit-listing-upload-images
  src/controllers/listing.js
  src/routes/listings.js
  src/routes/upload.js
Labels: Passed Code Review, Ready To Merge

#80 fix add transaction issue
  src/controllers/transaction.js
Labels: Ready For Code Review

#81 REV-11-claim-address-functionality
  src/controllers/claim-address.js
  src/migrations/20220324120655-create-claim-listing-address-table.js
  src/models/claim-listing-address.js
  src/models/index.js
  src/models/listing.js
  src/routes/claim-address.js
  src/routes/index.js
  src/swagger.yml
Labels: In Code Review, Comments Addressed

#84 REV-510 add garages to backend
  src/controllers/listing.js
Labels: In Code Review, Comments Addressed

#83 search query optimization
  src/models/listing.js
Labels: Ready For Code Review

#85 add change-password endpoint
  src/controllers/auth.js
  src/routes/auth.js
Labels: Ready For Code Review
